/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */


public class ViewEdad extends javax.swing.JPanel {

   

    /**
     * Creates new form ViewNotas
     */
    public ViewEdad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jinframe_edad = new javax.swing.JInternalFrame();
        jl_año = new javax.swing.JLabel();
        jtf_año = new javax.swing.JTextField();
        jl_edad = new javax.swing.JLabel();
        jbtn_calcular = new javax.swing.JButton();
        jl_edadd = new javax.swing.JLabel();

        jinframe_edad.setClosable(true);
        jinframe_edad.setIconifiable(true);
        jinframe_edad.setMaximizable(true);
        jinframe_edad.setResizable(true);
        jinframe_edad.setTitle("Edad");
        jinframe_edad.setVisible(true);

        jl_año.setText("Ingresa el año:");

        jl_edad.setText("***EDAD***");

        jbtn_calcular.setText("Calcular");

        javax.swing.GroupLayout jinframe_edadLayout = new javax.swing.GroupLayout(jinframe_edad.getContentPane());
        jinframe_edad.getContentPane().setLayout(jinframe_edadLayout);
        jinframe_edadLayout.setHorizontalGroup(
            jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jinframe_edadLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jl_año, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467))
            .addGroup(jinframe_edadLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_edadd, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jinframe_edadLayout.setVerticalGroup(
            jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jinframe_edadLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_año, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_edadd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtn_calcular)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jinframe_edad)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jinframe_edad)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_calcular;
    public static javax.swing.JInternalFrame jinframe_edad;
    private javax.swing.JLabel jl_año;
    public javax.swing.JLabel jl_edad;
    public javax.swing.JLabel jl_edadd;
    public javax.swing.JTextField jtf_año;
    // End of variables declaration//GEN-END:variables
}
