/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */

public class ViewNotas extends javax.swing.JPanel {

   

    /**
     * Creates new form ViewNotas
     */
    public ViewNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jinframe_edad = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtextarea_bloc = new javax.swing.JTextArea();
        jmbar_archivo = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_item_abrir = new javax.swing.JMenuItem();
        jm_item_guardar = new javax.swing.JMenuItem();
        jm_item_guardarcomo = new javax.swing.JMenuItem();
        jm_item_salir = new javax.swing.JMenuItem();

        jinframe_edad.setClosable(true);
        jinframe_edad.setIconifiable(true);
        jinframe_edad.setMaximizable(true);
        jinframe_edad.setResizable(true);
        jinframe_edad.setTitle("Bloc de Notas");
        jinframe_edad.setVisible(true);

        jtextarea_bloc.setColumns(20);
        jtextarea_bloc.setRows(5);
        jScrollPane2.setViewportView(jtextarea_bloc);

        jm_archivo.setText("Archivo");

        jm_item_abrir.setText("Abrir");
        jm_archivo.add(jm_item_abrir);

        jm_item_guardar.setText("Guardar");
        jm_archivo.add(jm_item_guardar);

        jm_item_guardarcomo.setText("Guardar como");
        jm_archivo.add(jm_item_guardarcomo);

        jm_item_salir.setText("Salir");
        jm_archivo.add(jm_item_salir);

        jmbar_archivo.add(jm_archivo);

        jinframe_edad.setJMenuBar(jmbar_archivo);

        javax.swing.GroupLayout jinframe_edadLayout = new javax.swing.GroupLayout(jinframe_edad.getContentPane());
        jinframe_edad.getContentPane().setLayout(jinframe_edadLayout);
        jinframe_edadLayout.setHorizontalGroup(
            jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jinframe_edadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        jinframe_edadLayout.setVerticalGroup(
            jinframe_edadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jinframe_edadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jinframe_edad)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jinframe_edad)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JInternalFrame jinframe_edad;
    private javax.swing.JMenu jm_archivo;
    public javax.swing.JMenuItem jm_item_abrir;
    public javax.swing.JMenuItem jm_item_guardar;
    public javax.swing.JMenuItem jm_item_guardarcomo;
    public javax.swing.JMenuItem jm_item_salir;
    private javax.swing.JMenuBar jmbar_archivo;
    public javax.swing.JTextArea jtextarea_bloc;
    // End of variables declaration//GEN-END:variables
}
