/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */
//Practica
public class ViewOrdenar extends javax.swing.JPanel {

   

    /**
     * Creates new form ViewNotas
     */
    public ViewOrdenar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jinframe_ordenar = new javax.swing.JInternalFrame();
        jl_numero = new javax.swing.JLabel();
        jtf_numero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_numeros = new javax.swing.JList<>();
        jbtn_ascendente = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_promedio = new javax.swing.JButton();
        jl_promedio = new javax.swing.JLabel();

        jinframe_ordenar.setClosable(true);
        jinframe_ordenar.setIconifiable(true);
        jinframe_ordenar.setMaximizable(true);
        jinframe_ordenar.setResizable(true);
        jinframe_ordenar.setTitle("Ordenar");
        jinframe_ordenar.setVisible(true);
        jinframe_ordenar.getContentPane().setLayout(null);

        jl_numero.setText("Ingresa un número:");
        jinframe_ordenar.getContentPane().add(jl_numero);
        jl_numero.setBounds(12, 26, 150, 24);
        jinframe_ordenar.getContentPane().add(jtf_numero);
        jtf_numero.setBounds(170, 30, 78, 24);

        jlist_numeros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlist_numeros);

        jinframe_ordenar.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 68, 128, 131);

        jbtn_ascendente.setText("Ordenar Ascendente");
        jinframe_ordenar.getContentPane().add(jbtn_ascendente);
        jbtn_ascendente.setBounds(160, 100, 200, 24);

        jbtn_agregar.setText("Agregar");
        jinframe_ordenar.getContentPane().add(jbtn_agregar);
        jbtn_agregar.setBounds(260, 30, 120, 24);

        jbtn_promedio.setText("Promedio");
        jinframe_ordenar.getContentPane().add(jbtn_promedio);
        jbtn_promedio.setBounds(180, 150, 130, 24);
        jinframe_ordenar.getContentPane().add(jl_promedio);
        jl_promedio.setBounds(70, 228, 129, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jinframe_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jinframe_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_ascendente;
    public javax.swing.JButton jbtn_promedio;
    public static javax.swing.JInternalFrame jinframe_ordenar;
    private javax.swing.JLabel jl_numero;
    public javax.swing.JLabel jl_promedio;
    public javax.swing.JList<String> jlist_numeros;
    public javax.swing.JTextField jtf_numero;
    // End of variables declaration//GEN-END:variables
}
